"""Write the ``.run-site-env.sh`` sourceable env export.

While a stack is running, run-site drops a small **shell** file at the
project root containing ``export KEY="value"`` statements for the
project-facing configuration (DB / Redis URLs, Django secret + allowed
hosts, and the libpq ``PG*`` vars). A developer in a second terminal can::

    source .run-site-env.sh
    python manage.py dbshell     # uses DATABASE_URL / DJANGO_*
    psql                         # uses PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD

The file is an *additional artifact* — run-site never reads it back; it
keeps injecting its subprocess env in-memory. It is created alongside the
``.run-site-config`` sidecar and removed on clean shutdown.

All the enabled/disabled logic lives in :func:`build_env_file_info`, which
reuses :func:`run_site.env.project_env_values` as the single source of
truth so this file never drifts from the in-memory subprocess env. The
rendering layer (:func:`_render`) is a dumb formatter over the resolved
``exports``.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

from run_site.config import RunSiteConfig
from run_site.env import (
    ContainerEndpoints,
    compute_allowed_hosts,
    effective_env_mapping,
    project_env_values,
)

logger = logging.getLogger(__name__)

ENV_FILENAME = ".run-site-env.sh"

# project_env_values() keys exported as URL/Django vars, in emission order.
# Their env-var *names* come from the project's [env] mapping (via
# effective_env_mapping), so a renamed DATABASE_URL flows through here too.
_MAPPED_KEYS: tuple[str, ...] = ("database_url", "redis_url", "secret_key", "allowed_hosts")

# Fixed libpq names → project_env_values() keys. Present only when real
# Postgres is running (those keys are absent in SQLite mode), so gating on
# ``db_host`` makes SQLite-mode omission automatic. These names are libpq
# conventions and are deliberately NOT remappable via [env].
_LIBPQ_KEYS: tuple[tuple[str, str], ...] = (
    ("PGHOST", "db_host"),
    ("PGPORT", "db_port"),
    ("PGDATABASE", "db_name"),
    ("PGUSER", "db_user"),
    ("PGPASSWORD", "db_password"),
)


@dataclass(frozen=True)
class EnvFileInfo:
    """Resolved ``(name, value)`` export pairs, in deterministic order."""

    exports: tuple[tuple[str, str], ...]


def build_env_file_info(
    *,
    config: RunSiteConfig,
    endpoints: ContainerEndpoints,
    secret_key: str | None,
    lan_hosts: tuple[str, ...],
) -> EnvFileInfo:
    """Resolve the export pairs for *config* + *endpoints*.

    Holds all the service-enabled/disabled logic; reuses
    :func:`project_env_values` and :func:`effective_env_mapping` so the
    output matches what the in-memory subprocess env would carry.
    """

    allowed_hosts = compute_allowed_hosts(bind=config.django.runserver_bind, lan_hosts=lan_hosts)
    values = project_env_values(
        config, endpoints, secret_key=secret_key, allowed_hosts=allowed_hosts
    )
    mapping = effective_env_mapping(config.env.mapping)

    exports: list[tuple[str, str]] = []
    for key in _MAPPED_KEYS:
        name = mapping.get(key)
        value = values.get(key)
        if name is not None and value is not None:
            exports.append((name, value))

    if "db_host" in values:  # real Postgres running (absent in SQLite mode)
        for pg_name, value_key in _LIBPQ_KEYS:
            value = values.get(value_key)
            if value is not None:
                exports.append((pg_name, value))

    return EnvFileInfo(exports=tuple(exports))


def env_file_path(project_root: Path) -> Path:
    """Where the env file lives for *project_root*."""

    return (project_root / ENV_FILENAME).resolve()


def write_env_file(*, project_root: Path, info: EnvFileInfo) -> Path:
    """Write ``<project_root>/.run-site-env.sh``, overwriting any stale copy.

    Returns the absolute path written.
    """

    path = env_file_path(project_root)
    path.write_text(_render(info), encoding="utf-8")
    return path


def remove_env_file(*, project_root: Path) -> None:
    """Best-effort delete. Logs but never raises."""

    path = env_file_path(project_root)
    try:
        path.unlink()
    except FileNotFoundError:
        pass  # Already gone — shutdown ran twice or the user removed it.
    except OSError:
        logger.exception("Failed to remove env file at %s", path)


def _render(info: EnvFileInfo) -> str:
    lines = [
        "# Auto-generated by run-site. Recreated on each start, removed on clean",
        "# shutdown. Contains secrets — keep `.run-site-env.sh` out of version control.",
        "#",
        f"# Usage:  source {ENV_FILENAME}",
        "",
    ]
    lines.extend(f"export {name}={_sh_double_quote(value)}" for name, value in info.exports)
    lines.append("")
    return "\n".join(lines)


def _sh_double_quote(value: str) -> str:
    """Render *value* as a bash double-quoted literal.

    Escapes the four characters special inside double quotes (``\\``,
    ``"``, ``` ` ```, ``$``) so a secret containing any of them survives a
    ``source`` with its exact bytes intact.
    """

    out = ['"']
    for ch in value:
        if ch in ("\\", '"', "`", "$"):
            out.append("\\")
        out.append(ch)
    out.append('"')
    return "".join(out)
