"""Read/write the ``.run-site-config`` sidecar file.

When a stack is running, run-site drops a small TOML file at the project
root that records the runtime endpoints — Postgres / Redis / web port —
plus connection URLs. The file is created **before** the runserver
starts so that companion tooling (e.g. ``django-dev-helpers``) can read
it during Django bootstrap. It is removed on clean shutdown.

The format is intentionally a superset of the env-var contract so a
non-Django consumer can pick everything it needs from one file.
"""

from __future__ import annotations

import datetime as dt
import logging
import urllib.parse
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

SIDECAR_FILENAME = ".run-site-config"


def _toml_basic_string(value: str) -> str:
    """Render *value* as a TOML basic string literal.

    TOML basic strings need backslash, quote, and control chars escaped;
    otherwise a password containing ``"`` or ``\\`` would produce invalid
    TOML and break readers like ``tomllib``.
    """

    out: list[str] = ['"']
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\b":
            out.append("\\b")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\f":
            out.append("\\f")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


@dataclass(frozen=True)
class SidecarInfo:
    """Everything the sidecar file records — gathered by the run flow.

    ``pg_*`` and ``redis_*`` fields are ``None`` when the corresponding
    service was disabled in config and therefore never started; in that
    case the entire ``[postgres]`` / ``[redis]`` section is omitted from
    the rendered sidecar file.
    """

    project_slug: str
    web_host: str
    web_port: int
    pg_host: str | None
    pg_port: int | None
    pg_db: str | None
    pg_user: str | None
    pg_password: str | None
    redis_host: str | None
    redis_port: int | None
    redis_db: int | None
    celery_enabled: bool
    celery_app: str | None


def sidecar_path(project_root: Path) -> Path:
    """Where the sidecar file lives for *project_root*."""

    return (project_root / SIDECAR_FILENAME).resolve()


def write_sidecar(*, project_root: Path, info: SidecarInfo) -> Path:
    """Write the sidecar TOML to ``<project_root>/.run-site-config``.

    Overwrites any existing file (e.g. left over from a crashed run).
    Returns the absolute path written.
    """

    path = sidecar_path(project_root)
    path.write_text(_render(info), encoding="utf-8")
    return path


def remove_sidecar(*, project_root: Path) -> None:
    """Best-effort delete. Logs but never raises."""

    path = sidecar_path(project_root)
    try:
        path.unlink()
    except FileNotFoundError:
        pass  # Already gone — not an error: shutdown ran twice or user removed it.
    except OSError:
        logger.exception("Failed to remove sidecar at %s", path)


def _render(info: SidecarInfo) -> str:
    generated = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    s = _toml_basic_string

    lines: list[str] = [
        "# Auto-generated by run-site. Records runtime endpoints of the",
        "# currently-running dev stack. Removed on clean shutdown — add",
        "# `.run-site-config` to .gitignore.",
        "",
        f"project_slug = {s(info.project_slug)}",
        f"generated_at = {s(generated)}",
        "",
        "[web]",
        f"host = {s(info.web_host)}",
        f"port = {info.web_port}",
        f"url = {s(f'http://{info.web_host}:{info.web_port}/')}",
    ]

    if (
        info.pg_host is not None
        and info.pg_port is not None
        and info.pg_db is not None
        and info.pg_user is not None
        and info.pg_password is not None
    ):
        # URL-encode user/password — same contract as build_subprocess_env so
        # values containing ``@``, ``/``, ``:``, spaces or other reserved
        # chars produce a parseable connection URL.
        quoted_user = urllib.parse.quote(info.pg_user, safe="")
        quoted_pwd = urllib.parse.quote(info.pg_password, safe="")
        pg_url = f"postgres://{quoted_user}:{quoted_pwd}@{info.pg_host}:{info.pg_port}/{info.pg_db}"
        lines.extend(
            [
                "",
                "[postgres]",
                f"host = {s(info.pg_host)}",
                f"port = {info.pg_port}",
                f"db = {s(info.pg_db)}",
                f"user = {s(info.pg_user)}",
                f"password = {s(info.pg_password)}",
                f"url = {s(pg_url)}",
            ]
        )

    if info.redis_host is not None and info.redis_port is not None and info.redis_db is not None:
        redis_url = f"redis://{info.redis_host}:{info.redis_port}/{info.redis_db}"
        lines.extend(
            [
                "",
                "[redis]",
                f"host = {s(info.redis_host)}",
                f"port = {info.redis_port}",
                f"db = {info.redis_db}",
                f"url = {s(redis_url)}",
            ]
        )

    lines.extend(
        [
            "",
            "[celery]",
            f"enabled = {str(info.celery_enabled).lower()}",
        ]
    )
    if info.celery_app:
        lines.append(f"app = {s(info.celery_app)}")
    lines.append("")
    return "\n".join(lines)
