"""Read/write the ``.run-site-config`` sidecar file.

When a stack is running, run-site drops a small TOML file at the project
root that records the runtime endpoints — Postgres / Redis / web port —
plus connection URLs. The file is created **before** the runserver
starts so that companion tooling (e.g. ``django-dev-helpers``) can read
it during Django bootstrap. It is removed on clean shutdown.

The format is intentionally a superset of the env-var contract so a
non-Django consumer can pick everything it needs from one file.
"""

from __future__ import annotations

import datetime as dt
import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

SIDECAR_FILENAME = ".run-site-config"


@dataclass(frozen=True)
class SidecarInfo:
    """Everything the sidecar file records — gathered by the run flow."""

    project_slug: str
    web_host: str
    web_port: int
    pg_host: str
    pg_port: int
    pg_db: str
    pg_user: str
    pg_password: str
    redis_host: str
    redis_port: int
    redis_db: int
    celery_enabled: bool
    celery_app: str | None


def sidecar_path(project_root: Path) -> Path:
    """Where the sidecar file lives for *project_root*."""

    return (project_root / SIDECAR_FILENAME).resolve()


def write_sidecar(*, project_root: Path, info: SidecarInfo) -> Path:
    """Write the sidecar TOML to ``<project_root>/.run-site-config``.

    Overwrites any existing file (e.g. left over from a crashed run).
    Returns the absolute path written.
    """

    path = sidecar_path(project_root)
    path.write_text(_render(info), encoding="utf-8")
    return path


def remove_sidecar(*, project_root: Path) -> None:
    """Best-effort delete. Logs but never raises."""

    path = sidecar_path(project_root)
    try:
        path.unlink()
    except FileNotFoundError:
        pass  # Already gone — not an error: shutdown ran twice or user removed it.
    except OSError:
        logger.exception("Failed to remove sidecar at %s", path)


def _render(info: SidecarInfo) -> str:
    generated = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    pg_url = (
        f"postgres://{info.pg_user}:{info.pg_password}"
        f"@{info.pg_host}:{info.pg_port}/{info.pg_db}"
    )
    redis_url = f"redis://{info.redis_host}:{info.redis_port}/{info.redis_db}"

    lines: list[str] = [
        "# Auto-generated by run-site. Records runtime endpoints of the",
        "# currently-running dev stack. Removed on clean shutdown — add",
        "# `.run-site-config` to .gitignore.",
        "",
        f'project_slug = "{info.project_slug}"',
        f'generated_at = "{generated}"',
        "",
        "[web]",
        f'host = "{info.web_host}"',
        f"port = {info.web_port}",
        f'url = "http://{info.web_host}:{info.web_port}/"',
        "",
        "[postgres]",
        f'host = "{info.pg_host}"',
        f"port = {info.pg_port}",
        f'db = "{info.pg_db}"',
        f'user = "{info.pg_user}"',
        f'password = "{info.pg_password}"',
        f'url = "{pg_url}"',
        "",
        "[redis]",
        f'host = "{info.redis_host}"',
        f"port = {info.redis_port}",
        f"db = {info.redis_db}",
        f'url = "{redis_url}"',
        "",
        "[celery]",
        f"enabled = {str(info.celery_enabled).lower()}",
    ]
    if info.celery_app:
        lines.append(f'app = "{info.celery_app}"')
    lines.append("")
    return "\n".join(lines)
